name: Piso Exp MG2
on:
  workflow_dispatch:        # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Restaurar hxh.json
        shell: bash
        run: |
          echo "$GCP_JSON_BASE64" | base64 -d > hxh.json
        env:
          GCP_JSON_BASE64: ${{ secrets.GCP_JSON_BASE64 }}

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Executar o script
        run: xvfb-run python main.py
